# Generated by Django 2.2.16 on 2022-10-19 16:14

from django.db import migrations, models
import reviews.validations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221019_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validations.time_validation]),
        ),
    ]
